#!/bin/bash

# Manual Deployment Steps
# Run these commands ON THE SERVER after SSH connection

echo "========================================="
echo "VBG App - Manual Deployment Steps"
echo "========================================="
echo ""
echo "1. SSH into the server:"
echo "   ssh -p 65002 u929905618@217.196.55.218"
echo ""
echo "2. Create app directory:"
echo "   mkdir -p ~/domains/app.veribuilds.com/vbg-app"
echo ""
echo "3. From your LOCAL machine, sync files:"
echo "   rsync -avz --progress -e \"ssh -p 65002\" \\"
echo "     --exclude 'node_modules' \\"
echo "     --exclude '.git' \\"
echo "     --exclude '.DS_Store' \\"
echo "     --exclude '*.log' \\"
echo "     --exclude '.env' \\"
echo "     --exclude '.env.local' \\"
echo "     --exclude 'rooster.db' \\"
echo "     --exclude 'uploads/*' \\"
echo "     --exclude 'contracts/*' \\"
echo "     --exclude 'logs/*' \\"
echo "     ./ \\"
echo "     u929905618@217.196.55.218:~/domains/app.veribuilds.com/vbg-app/"
echo ""
echo "4. Back on the SERVER, navigate to app:"
echo "   cd ~/domains/app.veribuilds.com/vbg-app"
echo ""
echo "5. Install dependencies:"
echo "   npm install"
echo ""
echo "6. Create .env file:"
echo "   cp env.production.example .env"
echo "   nano .env"
echo ""
echo "   REQUIRED: Update these values in .env:"
echo "   - JWT_SECRET (generate: openssl rand -base64 32)"
echo "   - EMAIL_USER"
echo "   - EMAIL_PASS"
echo ""
echo "7. Build the application:"
echo "   npm run build"
echo ""
echo "8. Install PM2 (if not installed):"
echo "   npm install -g pm2"
echo ""
echo "9. Start the application:"
echo "   pm2 start ecosystem.config.cjs"
echo ""
echo "10. Save PM2 configuration:"
echo "    pm2 save"
echo "    pm2 startup"
echo ""
echo "11. Check status:"
echo "    pm2 status"
echo "    pm2 logs"
echo ""
echo "========================================="
echo "Access your app at:"
echo "  http://app.veribuild.com:3000"
echo "  http://app.veribuild.com:4000/api/health"
echo "========================================="
